title: GOAT
author: Kyle Liu
email: kyleliu@comcast.net
description: > # this means to ignore newlines until "baseurl:"
  I'm so cool. 10th Grade. Dope as heck. Please follow me on Instagram.

# social links
github_username:  Kaliu1 # DO NOT include the @ character, or else the build will fail!
instagram_username: thekyleliu
facebook_username: thekyleliu


show_excerpts: true # set to false to remove excerpts on the homepage

theme: hacker
